name: "Rachel Nabors, award-winning cartoonist turned front-end developer"
description: "Where I post musigins about web development, comics, and the future of online interaction."

url: "http://localhost:4000" #http://rachelnabors.com

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true